# .github/workflows/extractor.yml

name: Daily Library Extractor

on:
  workflow_dispatch:
  schedule:
    - cron: '12 10 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Create output directory
        run: mkdir -p output
      
      - name: Run extractor
        env:
          GOLEMIO_API_KEY: ${{ secrets.GOLEMIO_API_KEY }}
        run: python main.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries
          path: output/libraries.csv